// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uytiwodjtulpjvgjtsod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5dGl3b2RqdHVscGp2Z2p0c29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzAwNzUsImV4cCI6MjA2OTkwNjA3NX0.p_ss1MSfiy4fuRZV6UqO-y90HWjGiMs78knSX8HSlRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});