[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "pyppeteer>=2.0.0",
    "pytrends>=4.9.2",
    "requests>=2.32.4",
    "youtube-transcript-api>=1.1.1",
]
